import React from "react";
import Head from "next/head";

export default function Header() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="h-16 max-w-screen-md mb-2 m-auto dark:border-emerald-800 border-2"></nav>
    </>
  );
}
