import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="dark:bg-slate-900 dark:text-white min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pt-8">
        <div className="h-16 max-w-screen-md mb-2 m-auto dark:border-emerald-800 border-2"></div>
        <div className="p-2 flex max-w-screen-md m-auto border-2 dark:border-violet-800">
          <Image
            src="/potrait.jpg"
            width={220}
            height={220}
            alt="Potrait of me"
            quality={100}
            placeholder="blur"
            blurDataURL="/potrait.jpg"
            className="rounded-full"
          />
          <div className="ml-4">
            <div>Based in Vietnam</div>
            <div>quangman1404@gmail.com</div>
            <div>Facebook</div>
            <div>Instagram</div>
            <div>Linkedin</div>
          </div>
        </div>
      </main>

      <footer className="m-auto max-w-screen-md flex justify-between">
        <span>© 2021 Man Pham</span>
        <span>Created with Next.js and Chakra UI</span>
        <span>© 2021 Man Pham</span>
      </footer>
    </div>
  );
};

export default Home;
