import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import Section from "../components/Section";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="dark:bg-slate-900 dark:text-white min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pt-8">
        <nav className="h-16 max-w-screen-md mb-2 m-auto dark:border-emerald-800 border-2"></nav>
        <div className="p-2 max-w-screen-md m-auto border-2 dark:border-violet-800">
          <Section className="flex">
            <Image
              src="/potrait.jpg"
              width={220}
              height={220}
              alt="Portrait of me"
              quality={100}
              placeholder="blur"
              blurDataURL="/portrait.jpg"
              className="rounded-full"
            />
            <div className="ml-4">
              <div>Based in Vietnam</div>
              <div>quangman1404@gmail.com</div>
              <div>Facebook</div>
              <div>Instagram</div>
              <div>Linkedin</div>
            </div>
          </Section>
          <Section>
            <h4>👋🏻 Hello!</h4>
            <p>
              My name is Mẫn, a Fullstack Web Developer with over 5 years of
              experience. I am also an undergraduate enrolled in Bachelor of
              Information Technology at RMIT University in Vietnam. <br />
              Aside from the web, I have dabbled in many other tech fields like
              Machine Learning, Penetration Testing, Video Games, etc. The more
              about my work can be found in experience.
            </p>
          </Section>
        </div>
      </main>

      <footer className="m-auto max-w-screen-md flex justify-between">
        <span>© 2021 Man Pham</span>
        <span>Created with Next.js and Chakra UI</span>
        <span>© 2021 Man Pham</span>
      </footer>
    </div>
  );
};

export default Home;
