import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="dark:bg-slate-900 dark:text-white min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pt-8">
        <div className="h-16 max-w-screen-md mb-2 m-auto border-emerald-800 border-2"></div>
        <div className="p-2 max-w-screen-md m-auto border-2 border-violet-800">
          <p className=" font-bold">Hello</p>
          <p>welcome to my site</p>
        </div>
      </main>

      <footer className="m-auto max-w-screen-md flex justify-between">
        <span>© 2021 Man Pham</span>
        <span>Created with Next.js and Chakra UI</span>
        <span>© 2021 Man Pham</span>
      </footer>
    </div>
  );
};

export default Home;
